FROM archlinux:latest

RUN pacman -Syu --noconfirm
RUN pacman -Syy --noconfirm
RUN pacman -S --needed git base-devel --noconfirm 
RUN pacman -S --noconfirm docker docker-compose docker-buildx
RUN useradd -m -G wheel builder && echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

RUN pacman -S --noconfirm glibc glibc-locales
RUN sed -i -e 's/#en_DK.UTF-8/en_DK.UTF-8/g' /etc/locale.gen

USER builder
WORKDIR /home/builder

RUN git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si --noconfirm

# .NET stack
RUN yay -S --noconfirm rider dotnet-sdk aspnet-runtime aspnet-runtime-8.0 dotnet-sdk-8.0 azure-functions-core-tools-bin
RUN dotnet tool install --global dotnet-ef
RUN wget -qO- https://aka.ms/install-artifacts-credprovider.sh | bash

# Rider dependencies
RUN yay -S --noconfirm libxkbcommon font-manager

# Microsoft tools
RUN yay -S --noconfirm azure-cli bicep-bin 

# JS stack
RUN yay -S --noconfirm nodejs npm yarn

# Android specific tooling
# RUN yay -S --noconfirm libxtst libxrender font-manager libxkbfile libbsd android-studio nss libpulse

USER root
