FROM archlinux:latest

RUN pacman -Syu --noconfirm
RUN pacman -S --needed git base-devel --noconfirm 
RUN useradd -m -G wheel builder && echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

USER builder
WORKDIR /home/builder

RUN git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si --noconfirm

RUN yay -S --noconfirm rider libxtst libxrender font-manager dotnet-sdk aspnet-runtime aspnet-runtime-8.0 dotnet-sdk-8.0 azure-functions-core-tools-bin

RUN yay -S --noconfirm azure-cli

RUN wget -qO- https://aka.ms/install-artifacts-credprovider.sh | bash

RUN dotnet tool install --global dotnet-ef

USER root
